package client.gui;

import client.model.Card;
import client.model.CardFrame;

import javax.swing.*;
import java.util.*;
/*
public class TableFrame extends JFrame {

    private Card card;
    private CardFrame cardLabel;


    public TableFrame() {
        initComponents();

        drawHand();                    
        
        drawBlackjack();            
    
    }
    
    private void drawBlackjack(){
        // cartas do dealer
        cardLabel = new CardFrame();
        //card = gameDeck.deal();
        cardLabel.setCardImage("bv");
        cardLabel.setCardCovered(false);
        cardLabel.setLocation(270,180);
        this.TablePanel.add(cardLabel);
        
        cardLabel = new CardFrame();

        cardLabel.setCardImage(card.getName());
        cardLabel.setCardCovered(false);
        cardLabel.setLocation(380,180);
        this.TablePanel.add(cardLabel);

        // cartas do player 1
        cardLabel = new CardFrame();
        cardLabel.setCardImage(card.getName());
        cardLabel.setCardCovered(true);
        cardLabel.setLocation(530,350);
        this.TablePanel.add(cardLabel);

        cardLabel = new CardFrame();
        cardLabel.setCardImage(card.getName());
        cardLabel.setCardCovered(false);
        cardLabel.setLocation(550,350);
        this.TablePanel.add(cardLabel);        
 
        // cartas do player 2
        cardLabel = new CardFrame();
        cardLabel.setCardImage(card.getName());
        cardLabel.setCardCovered(true);
        cardLabel.setLocation(300,350);
        this.TablePanel.add(cardLabel);

        cardLabel = new CardFrame();
        cardLabel.setCardImage(card.getName());
        cardLabel.setCardCovered(false);
        cardLabel.setLocation(320,350);
        this.TablePanel.add(cardLabel); 
        
        // cartas do player 3
        cardLabel = new CardFrame();
        cardLabel.setCardImage(card.getName());
        cardLabel.setCardCovered(true);
        cardLabel.setLocation(80,350);
        this.TablePanel.add(cardLabel);

        cardLabel = new CardFrame();
        cardLabel.setCardImage(card.getName());
        cardLabel.setCardCovered(false);
        cardLabel.setLocation(100,350);
        this.TablePanel.add(cardLabel);          
    }

    // apresenta as 13 primeiras cartas do deck (para teste apenas)
    private void drawHand(){

        CardFrame [] myCardLabels = new CardFrame[13];
        List<CardFrame> labelList = new ArrayList<CardFrame>();
        
        for(int i=0; i<13; i++){
           myCardLabels[i] = new CardFrame();            // cria o label da carta (vazio)
           this.TablePanel.add(myCardLabels[i]);         // adiciona a carta no panel da mesa
        }
        Card [] myHand = gameDeck.getHand();   // obtem as cartas 
        
        // para cada carta
        for(int i=0; i< myHand.length; i++){
            labelList.add(myCardLabels[i]);                     // adiciona o label numa lista    
            myCardLabels[i].setCardImage(myHand[i].getName());  // define a imagem da carta

        }      
       
        // posiciona as cartas 
        boolean covered = true;
        int nCards = labelList.size();
        for(int i=0; i<nCards; i++){
           if(i==(nCards - 1)) covered = false;  // a última é totalmente visivel
           labelList.get(i).setCardCovered(covered);
           labelList.get(i).setLocation(200+i*20,20);
        }
    }
    */

/*
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    /*@SuppressWarnings("unchecked")*/
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    /*private void initComponents() {

        TablePanel = new JPanel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Card Game GUI");
        setPreferredSize(new java.awt.Dimension(762, 550));
        setResizable(false);

        TablePanel.setBackground(new java.awt.Color(0, 153, 0));
        TablePanel.setPreferredSize(new java.awt.Dimension(762, 550));

        GroupLayout TablePanelLayout = new GroupLayout(TablePanel);
        TablePanel.setLayout(TablePanelLayout);
        TablePanelLayout.setHorizontalGroup(
            TablePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        TablePanelLayout.setVerticalGroup(
            TablePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TablePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(TablePanel, GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
*/
    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel TablePanel;
    // End of variables declaration//GEN-END:variables

}*/